INSERT INTO USER (ID, USERNAME, PASSWORD, ROLE) VALUES
(nextval('USER_SEQ'), 'admin', '$2a$10$9MIX8kYPkuB7uE/H5nHF8.KG6.YdjBA/voOnjSZnZDxLXL/2BIerS', 'ADMIN');
INSERT INTO USER (ID, USERNAME, PASSWORD, ROLE) VALUES
(nextval('USER_SEQ'), 'marie', '$2a$10$pQnldtWyD5CpMBjWJycMW.jmEOY2zKqjSkCo5V2vKqvW44ORrdpAa', 'USER');
INSERT INTO USER (ID, USERNAME, PASSWORD, ROLE) VALUES
(nextval('USER_SEQ'), 'giraf', '$2a$10$pQnldtWyD5CpMBjWJycMW.jmEOY2zKqjSkCo5V2vKqvW44ORrdpAa', 'USER');
INSERT INTO USER (ID, USERNAME, PASSWORD, ROLE) VALUES
(nextval('USER_SEQ'), 'olifant', '$2a$10$pQnldtWyD5CpMBjWJycMW.jmEOY2zKqjSkCo5V2vKqvW44ORrdpAa', 'USER');
INSERT INTO USER (ID, USERNAME, PASSWORD, ROLE) VALUES
(nextval('USER_SEQ'), 'ezel', '$2a$10$pQnldtWyD5CpMBjWJycMW.jmEOY2zKqjSkCo5V2vKqvW44ORrdpAa', 'USER');
INSERT INTO USER (ID, USERNAME, PASSWORD, ROLE) VALUES
(nextval('USER_SEQ'), 'varaan', '$2a$10$pQnldtWyD5CpMBjWJycMW.jmEOY2zKqjSkCo5V2vKqvW44ORrdpAa', 'USER');
INSERT INTO USER (ID, USERNAME, PASSWORD, ROLE) VALUES
(nextval('USER_SEQ'), 'hond', '$2a$10$pQnldtWyD5CpMBjWJycMW.jmEOY2zKqjSkCo5V2vKqvW44ORrdpAa', 'USER');
INSERT INTO USER (ID, USERNAME, PASSWORD, ROLE) VALUES
(nextval('USER_SEQ'), 'aap', '$2a$10$pQnldtWyD5CpMBjWJycMW.jmEOY2zKqjSkCo5V2vKqvW44ORrdpAa', 'USER');
INSERT INTO USER (ID, USERNAME, PASSWORD, ROLE) VALUES
(nextval('USER_SEQ'), 'kip', '$2a$10$pQnldtWyD5CpMBjWJycMW.jmEOY2zKqjSkCo5V2vKqvW44ORrdpAa', 'USER');